### ISSUE TITLE
Action.tpl needs to be updated for 4.5

### ISSUE THREAD

**Issue by jmcclelland** [eileenmcnaughton/nz.co.fuzion.reportbase#4]
The new Actions.tpl uses the new drop down select code for choosing a group to add results to.

I'm also having trouble figuring out why this template is overridden in reportbase. It seems to be overridden in extendedreports and advancedfundraising (almost the same changes).

**Comment by eileenmcnaughton** [comment]
Yeah - it can go

**Comment by eileenmcnaughton** [comment]
I'm going to kill out the criteria.tpl from this too.

Having this separate to extendedreports / fundraising reports as a shared extension hasn't really worked so I expect to phase out this extensions
